add a script to export pwd as PYTHONPATH
if we want to execute python alone, we need it to avoid the below problem:

python3 app/modules/profilers/memory/MemoryProfiler.py
Traceback (most recent call last):
  File "app/modules/profilers/memory/MemoryProfiler.py", line 9, in <module>
    from app.modules.lepd.LepDClient import LepDClient
ModuleNotFoundError: No module named 'app'

now we need to do:
. exportpythonpath.sh

Signed-off-by: Barry Song <21cnbao@gmail.com>